work_dir: ./models/X-Sub
weights: ./models/X-Sub/epoch75_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:

  data_path: ../data/ntu_300/xsub/val_data_joint.npy
  label_path: ../data/ntu_300/xsub/val_label.pkl
# model
model: net.SAmotif_stgcn_PTDB.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0
  edge_importance_weighting: False
  pyramid_pool: False
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  vtdb_args:
    interc: 1
    gr: 8
# test 
phase: test
device: [0,1]
test_batch_size: 64
