work_dir: ./work_dir/ntu-xview/models
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../data/ntu_300/xview/train_data_joint.npy
  label_path: ../data/ntu_300/xview/train_label.pkl
test_feeder_args:
  data_path: ../data/ntu_300/xview/val_data_joint.npy
  label_path: ../data/ntu_300/xview/val_label.pkl

# model
model: net.SAmotif_stgcn_PTDB.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0
  edge_importance_weighting: False
  pyramid_pool: False
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
#    max_hop: 1
  vtdb_args:
    interc: 1
    gr: 4


#optim
lamda_r: 0.00014
weight_decay: 0.0001
base_lr: 0.1
step: [40]

#training
optimizer: 'SGD'
device: [0,1,2,3,4,5,6.7]
batch_size: 64
test_batch_size: 64
num_epoch: 80



